import React from "react";

// @ts-expect-error - This is an autogenerated file that will be overwritten or replaced by the build process
import createOddVoicesModule from "./js/oddvoices_wasm.mjs";
import { OddVoiceJSON } from "../oddVoiceJSON/oddVoiceHelpers";
import { Voice } from "./oddvoicesUtils";

export const useOddVoicesApp = () => {
    const [oddVoiceApp, setOddVoiceApp] = React.useState<{
        sing: (voice: Voice, input: string, output: string, lyricsOverride: string) => string;
        FS: {
            readFile: (filename: string) => Uint8Array;
        }
    } | null>(null);

    React.useEffect(() => {
        const initialize = async () => setOddVoiceApp(await createOddVoicesModule());
        initialize();
    }, []);

    const generateVoiceFromOddVoiceJson = (oddVoiceJson: OddVoiceJSON): Uint8Array | undefined => {
        if (!oddVoiceApp) {
            console.error("OddVoice app not initialized");
            return;
        }
        const error: string = oddVoiceApp.sing(0, JSON.stringify(oddVoiceJson), "out.wav", "");
        if (error !== "") {
            console.error(error);
            return;
        }

        const buffer: Uint8Array = oddVoiceApp.FS.readFile("out.wav");
        if (!buffer || buffer.length === 0) {
            console.error("No buffer");
            return;
        }
        return buffer;
    };

    return {
        oddVoiceApp,
        generateVoiceFromOddVoiceJson,
    };
};
