import { OddVoiceJSON } from "../oddVoiceJSON/oddVoiceHelpers";
import { Voice } from "../oddvoices/oddvoicesUtils";
// @ts-expect-error - This is an autogenerated file that will be overwritten or replaced by the build process
import createOddVoicesModule from "../oddvoices/js/oddvoices_wasm.mjs";

// Setup the web worker context
const ctx: Worker = self as unknown as Worker;

// Track loaded voices
const loadedVoices: Record<string, boolean> = {};
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let oddVoiceApp: any = null;

// Initialize the OddVoices module
async function initializeModule() {
  try {
    oddVoiceApp = await createOddVoicesModule();
    oddVoiceApp.FS.mkdir("/voices/");
    ctx.postMessage({ status: "moduleReady" });
  } catch (error) {
    ctx.postMessage({
      status: "error",
      error: error instanceof Error ? error.message : String(error),
    });
  }
}

// Load a specific voice file
async function loadVoice(voice: Voice) {
  if (loadedVoices[voice]) {
    return true;
  }

  try {
    const response = await fetch(`voices/${voice}.voice`);
    if (!response.ok) {
      throw new Error(`Failed to fetch voice: ${voice}`);
    }

    const buffer = await response.arrayBuffer();
    const fileName = `/voices/${voice}.voice`;

    // Write the voice file to the virtual filesystem
    oddVoiceApp.FS.writeFile(fileName, new Uint8Array(buffer));
    loadedVoices[voice] = true;

    return true;
  } catch (error) {
    console.error(`Failed to load voice ${voice}:`, error);
    return false;
  }
}

// Generate audio from OddVoice JSON
async function generateVoice(oddVoiceJson: OddVoiceJSON, voice: Voice) {
  if (!oddVoiceApp) {
    throw new Error("OddVoice app not initialized");
  }

  // Load voice if not already loaded
  const voiceLoaded = await loadVoice(voice);
  if (!voiceLoaded) {
    throw new Error(`Failed to load voice: ${voice}`);
  }

  // Clean up any previous file if it exists
  try {
    oddVoiceApp.FS.unlink("out.wav");
  } catch (e) {
    // File might not exist, ignore
  }

  // Initialize voice
  const voiceData = new oddVoiceApp.Voice();
  voiceData.initFromFile(`/voices/${voice}.voice`);

  // Process the voice
  const error: string = oddVoiceApp.sing(
    voiceData,
    JSON.stringify(oddVoiceJson),
    "out.wav",
    ""
  );

  if (error !== "") {
    throw new Error(error);
  }

  // Read the output
  const buffer: Uint8Array = oddVoiceApp.FS.readFile("out.wav");
  if (!buffer || buffer.length === 0) {
    throw new Error("No output buffer generated");
  }

  return buffer;
}

// Listen for messages from the main thread
ctx.addEventListener("message", async (event) => {
  const { type, id, data } = event.data;

  try {
    if (type === "init") {
      await initializeModule();
    } else if (type === "generate") {
      if (!oddVoiceApp) {
        throw new Error("Module not initialized");
      }

      const { json, voice } = data;
      const audioBuffer = await generateVoice(json, voice);

      ctx.postMessage({
        id,
        status: "success",
        buffer: audioBuffer,
      });
    } else {
      throw new Error(`Unknown message type: ${type}`);
    }
  } catch (error) {
    ctx.postMessage({
      id,
      status: "error",
      error: error instanceof Error ? error.message : String(error),
    });
  }
});

// Start initialization
initializeModule();
